run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - bin
    - .git
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_gen\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  goconst:
    min-len: 3
    min-occurrences: 2
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  
  goimports:
    local-prefixes: github.com/ankurpal/distributed-task-queue
  
  govet:
    check-shadowing: true
  
  misspell:
    locale: US
  
  revive:
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning
      - name: package-comments
        severity: warning

linters:
  enable:
    - errcheck
    - goconst
    - gocritic
    - gofmt
    - goimports
    - golint
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - typecheck
    - unused
    - varcheck
  disable:
    - deadcode
    - structcheck
    - maligned

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - goconst
        - gocritic
        - gosec
        - revive
    - path: proto/
      linters:
        - revive
        - gocritic
  max-issues-per-linter: 0
  max-same-issues: 0

